FROM oven/bun:latest

ARG VITE_API_BASE_URL
ARG VITE_API_BASE_PORT
ARG VITE_API_GOOGLE_MAPS_KEY
ARG VITE_API_GOOGLE_MAPS_ID

ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_API_BASE_PORT=$VITE_API_BASE_PORT
ENV VITE_API_GOOGLE_MAPS_KEY=$VITE_API_GOOGLE_MAPS_KEY
ENV VITE_API_GOOGLE_MAPS_ID=$VITE_API_GOOGLE_MAPS_ID

EXPOSE 3000

ENV PORT 3000

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY package.json .

RUN bun install

COPY . .

RUN bun run build

CMD ["bun", "serve", "./dist"]